### ISSUE TITLE
ログインページのここかえる

### ISSUE THREAD

**Issue by nullnyat** [NullCatSlave/nca10.net#3]
![image](https://user-images.githubusercontent.com/89781396/153149185-0091ecaa-7897-452e-a6e9-3294ae6f6333.png)

**Comment by sim1222** [comment]
なににしたい？

**Comment by sim1222** [comment]
めも
https://github.com/NullCatSlave/nca10.net/blob/Ncat/packages/client/src/pages/welcome.entrance.a.vue

**Comment by nullnyat** [comment]
OK
